name: QA Automation CI

on:
  push:
    branches: [ master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        run: |
          cd backend-node
          npm install

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Start backend
        run: |
          cd backend-node
          npm start &
        env:
          CI: true

      - name: Wait for backend
        run: sleep 5

      - name: Run Cypress tests
        run: |
          cd frontend
          npx cypress run


